# Generated by Django 3.2.13 on 2022-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='private_profile',
            field=models.BooleanField(default=False, verbose_name='Приватность профиля'),
        ),
    ]
