# Generated by Django 3.2.12 on 2022-03-26 17:56

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('weight', models.PositiveSmallIntegerField(default=100, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('name', models.CharField(max_length=150)),
                ('text', models.TextField(help_text='Минимум два слова. Обязательно должно содержаться слово превосходно или роскошно', validators=[catalog.validators.validate_required_words, catalog.validators.validate_words_count], verbose_name='Текст')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='catalog.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(related_name='items', to='catalog.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
