# Generated by Django 3.2.12 on 2022-04-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220409_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Название'),
        ),
    ]
