# Generated by Django 3.2.12 on 2022-04-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Название'),
        ),
    ]
